import type { Metadata } from "next";
import "../globals.css";
import { manrope } from "@/utils/font";
import { SideBar } from "@/components/layout/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <div className="grid grid-cols-[300px_minmax(0px,1fr)]">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
